# First remove *all* keybindings
unbind-key -a

# Need for the Home and End Key to work in nvim
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# Now reinsert all the regular tmux keys
bind ^X lock-server
bind ^C new-window -c "$HOME"
bind ^D detach
# bind * list-clients

bind : command-prompt
bind r command-prompt "rename-window %%"
bind R source-file ~/.config/tmux/tmux.conf

bind '[' copy-mode

bind -r n next-window
bind -r p previous-window
bind ^A last-window
bind ^W list-windows
bind w list-windows
bind z resize-pane -Z
bind ^L refresh-client
bind l refresh-client

# Split windows
bind - split-window -v -c "#{pane_current_path}"
bind '/' split-window -h -c "#{pane_current_path}"

bind c kill-pane
bind x swap-pane -D

bind '"' choose-window
bind g choose-window
bind s choose-session

# # bind h select-pane -L
# # bind j select-pane -D
# # bind k select-pane -U
# # bind l select-pane -R
# bind -r h resize-pane -L 5
# bind -r j resize-pane -R 5
# bind -r k resize-pane -D 5
# bind -r l resize-pane -U 5

# bind-key -n 'M-h' resize-pane -L 5
# bind-key -n 'M-j' resize-pane -D 5
# bind-key -n 'M-k' resize-pane -U 5
# bind-key -n 'M-l' resize-pane -R 5

# Write in all panes simultaneous
bind * setw synchronize-panes
bind P set pane-border-status
bind R source-file ~/.config/tmux/tmux.conf
bind K send-keys "clear"\; send-keys "Enter"
bind-key -T copy-mode-vi v send-keys -X begin-selection
